# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GreenNav Project Wiki
description: > # this means to ignore newlines until "baseurl:"
  Wiki for Green Navigation, a prototypic system to compute energy-optimal routes and to predict the remaining crusing range for electric vehicles.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://greennav.github.io" # the base hostname & protocol for your site

gems:
  - jekyll-redirect-from

# Build settings
markdown: kramdown