siteTitle="GreenNav"
baseColor = "#1B5E20"
primaryColor = "#F05D21"
linkPrefix = "/greennav"
developmentPages = [
  "/development/",
  "/development/getting-started/",
  "/development/design-style-guide/",
  "/development/interface/",
  "/development/add-wiki-pages/",
  "/development/roadmap/",
]
docPages = [
  "/docs/",
  "/docs/getting-started/",
]
